/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projectBasdat;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author ASUS
 */
public class File extends javax.swing.JFrame {

    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    boolean isEditing;

    /**
     * Creates new form File
     */
    public File() {
        initComponents();
        conn = Koneksi.connectRb();
        initUI();
        populateTable();
    }

    public void initUI() {
        isEditing = false;
        updateButtons();
        updateFields();
    }

    public void updateButtons() {
        saveBtn.setEnabled(isEditing);
        updateBtn.setEnabled(isEditing);
        browseBtn1.setEnabled(isEditing);
        browseBtn2.setEnabled(isEditing);
        browseBtn3.setEnabled(isEditing);
        browseBtn4.setEnabled(isEditing);
        browseBtn5.setEnabled(isEditing);
        browseBtn6.setEnabled(isEditing);
    }

    public void updateFields() {
        idKlienTxt.setEnabled(isEditing);
        noLaiTxt.setEnabled(isEditing);
        laiTxt.setEnabled(isEditing);
        neracaTxt.setEnabled(isEditing);
        calkTxt.setEnabled(isEditing);
        labarugiTxt.setEnabled(isEditing);
        arusKasTxt.setEnabled(isEditing);
        keteranganTxt.setEnabled(isEditing);
    }

    private void populateTable() {
        String sqlQuery = "SELECT * FROM files";

        try {
            pst = conn.prepareStatement(sqlQuery);
            rs = pst.executeQuery();
            fileTbl.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    public void close() {
        WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        navAuditor = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        navInfoKlien = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        navHasilAudit = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        navLaporanKeuangan = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        navAfiliator = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        navFile = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        idKlienTxt = new javax.swing.JTextField();
        noLaiTxt = new javax.swing.JTextField();
        laiTxt = new javax.swing.JTextField();
        neracaTxt = new javax.swing.JTextField();
        calkTxt = new javax.swing.JTextField();
        labarugiTxt = new javax.swing.JTextField();
        arusKasTxt = new javax.swing.JTextField();
        keteranganTxt = new javax.swing.JTextField();
        browseBtn1 = new javax.swing.JButton();
        browseBtn2 = new javax.swing.JButton();
        browseBtn3 = new javax.swing.JButton();
        browseBtn4 = new javax.swing.JButton();
        browseBtn5 = new javax.swing.JButton();
        browseBtn6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        fileTbl = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        newBtn = new javax.swing.JButton();
        removeBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        searchTxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));

        navAuditor.setBackground(new java.awt.Color(0, 51, 102));
        navAuditor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                navAuditorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                navAuditorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                navAuditorMouseExited(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Poppins Medium", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Tabel Auditor");

        javax.swing.GroupLayout navAuditorLayout = new javax.swing.GroupLayout(navAuditor);
        navAuditor.setLayout(navAuditorLayout);
        navAuditorLayout.setHorizontalGroup(
            navAuditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navAuditorLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        navAuditorLayout.setVerticalGroup(
            navAuditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navAuditorLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addContainerGap())
        );

        navInfoKlien.setBackground(new java.awt.Color(0, 51, 102));
        navInfoKlien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                navInfoKlienMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                navInfoKlienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                navInfoKlienMouseExited(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Poppins Medium", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Informasi Klien");

        javax.swing.GroupLayout navInfoKlienLayout = new javax.swing.GroupLayout(navInfoKlien);
        navInfoKlien.setLayout(navInfoKlienLayout);
        navInfoKlienLayout.setHorizontalGroup(
            navInfoKlienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(navInfoKlienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(navInfoKlienLayout.createSequentialGroup()
                    .addGap(0, 32, Short.MAX_VALUE)
                    .addComponent(jLabel17)
                    .addGap(0, 36, Short.MAX_VALUE)))
        );
        navInfoKlienLayout.setVerticalGroup(
            navInfoKlienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(navInfoKlienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(navInfoKlienLayout.createSequentialGroup()
                    .addGap(0, 11, Short.MAX_VALUE)
                    .addComponent(jLabel17)
                    .addGap(0, 11, Short.MAX_VALUE)))
        );

        navHasilAudit.setBackground(new java.awt.Color(0, 51, 102));
        navHasilAudit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                navHasilAuditMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                navHasilAuditMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                navHasilAuditMouseExited(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Poppins Medium", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Laporan Hasil Audit");

        javax.swing.GroupLayout navHasilAuditLayout = new javax.swing.GroupLayout(navHasilAudit);
        navHasilAudit.setLayout(navHasilAuditLayout);
        navHasilAuditLayout.setHorizontalGroup(
            navHasilAuditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navHasilAuditLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel16)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        navHasilAuditLayout.setVerticalGroup(
            navHasilAuditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navHasilAuditLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        navLaporanKeuangan.setBackground(new java.awt.Color(0, 51, 102));
        navLaporanKeuangan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                navLaporanKeuanganMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                navLaporanKeuanganMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                navLaporanKeuanganMouseExited(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Poppins Medium", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Laporan Keuangan ");
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout navLaporanKeuanganLayout = new javax.swing.GroupLayout(navLaporanKeuangan);
        navLaporanKeuangan.setLayout(navLaporanKeuanganLayout);
        navLaporanKeuanganLayout.setHorizontalGroup(
            navLaporanKeuanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navLaporanKeuanganLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addGap(18, 18, 18))
        );
        navLaporanKeuanganLayout.setVerticalGroup(
            navLaporanKeuanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navLaporanKeuanganLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addContainerGap())
        );

        navAfiliator.setBackground(new java.awt.Color(0, 51, 102));
        navAfiliator.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                navAfiliatorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                navAfiliatorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                navAfiliatorMouseExited(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Poppins Medium", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Afiliator");

        javax.swing.GroupLayout navAfiliatorLayout = new javax.swing.GroupLayout(navAfiliator);
        navAfiliator.setLayout(navAfiliatorLayout);
        navAfiliatorLayout.setHorizontalGroup(
            navAfiliatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navAfiliatorLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel20)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        navAfiliatorLayout.setVerticalGroup(
            navAfiliatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navAfiliatorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addContainerGap())
        );

        navFile.setBackground(new java.awt.Color(0, 102, 153));
        navFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                navFileMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                navFileMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                navFileMouseExited(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Poppins Medium", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("File ");

        javax.swing.GroupLayout navFileLayout = new javax.swing.GroupLayout(navFile);
        navFile.setLayout(navFileLayout);
        navFileLayout.setHorizontalGroup(
            navFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navFileLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jLabel22)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        navFileLayout.setVerticalGroup(
            navFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navFileLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Poppins", 3, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("AM");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(navAuditor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(navInfoKlien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(navHasilAudit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(navLaporanKeuangan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(navAfiliator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(navFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(navInfoKlien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(navAuditor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(navHasilAudit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(navLaporanKeuangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(navAfiliator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(navFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(218, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel1.setText("ID Klien");

        jLabel2.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel2.setText("No. LAI ");

        jLabel3.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel3.setText("File LAI");

        jLabel5.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel5.setText("File Neraca");

        jLabel6.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel6.setText("File Laba/Rugi");

        jLabel7.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel7.setText("File Arus Kas");

        jLabel8.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel8.setText("File CALK");

        jLabel9.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel9.setText("File Keterangan");

        browseBtn1.setText("Browse");
        browseBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseBtn1ActionPerformed(evt);
            }
        });

        browseBtn2.setText("Browse");
        browseBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseBtn2ActionPerformed(evt);
            }
        });

        browseBtn3.setText("Browse");
        browseBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseBtn3ActionPerformed(evt);
            }
        });

        browseBtn4.setText("Browse");
        browseBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseBtn4ActionPerformed(evt);
            }
        });

        browseBtn5.setText("Browse");
        browseBtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseBtn5ActionPerformed(evt);
            }
        });

        browseBtn6.setText("Browse");
        browseBtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseBtn6ActionPerformed(evt);
            }
        });

        fileTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID ", "No. LAI", "File LAI", "File Neraca", "File CALK", "File Laba/Rugi", "File Arus Kas", "File Keterangan"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        fileTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fileTblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(fileTbl);

        jLabel18.setFont(new java.awt.Font("Poppins", 1, 36)); // NOI18N
        jLabel18.setText("FILE");

        newBtn.setText("New");
        newBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newBtnActionPerformed(evt);
            }
        });

        removeBtn.setText("Remove");
        removeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBtnActionPerformed(evt);
            }
        });

        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel14.setText("Search by ID Klien");

        searchTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchTxtKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(neracaTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                                            .addComponent(laiTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                                            .addComponent(calkTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                                            .addComponent(noLaiTxt)
                                            .addComponent(idKlienTxt))
                                        .addGap(42, 42, 42)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(browseBtn1)
                                            .addComponent(browseBtn2)
                                            .addComponent(browseBtn3))
                                        .addGap(51, 51, 51)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel9))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labarugiTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(arusKasTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(keteranganTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(42, 42, 42)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(browseBtn4)
                                            .addComponent(browseBtn5)
                                            .addComponent(browseBtn6)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addGap(40, 40, 40)
                                        .addComponent(searchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(newBtn)
                                        .addGap(18, 18, 18)
                                        .addComponent(removeBtn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(updateBtn)
                                        .addGap(18, 18, 18)
                                        .addComponent(saveBtn)))
                                .addGap(617, 617, 617))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(504, 504, 504)
                        .addComponent(jLabel18)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(idKlienTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(noLaiTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(laiTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(browseBtn1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(neracaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(browseBtn2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(calkTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(browseBtn3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(labarugiTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(browseBtn4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(arusKasTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(browseBtn5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(keteranganTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(browseBtn6))))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBtn)
                    .addComponent(updateBtn)
                    .addComponent(removeBtn)
                    .addComponent(newBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void navAuditorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navAuditorMouseClicked
        // TODO add your handling code here:
        FormAuditor fa = new FormAuditor();
        close();

        fa.show();
    }//GEN-LAST:event_navAuditorMouseClicked

    private void navAuditorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navAuditorMouseEntered
        // TODO add your handling code here:
        navAuditor.setCursor(new Cursor(Cursor.HAND_CURSOR));
        navAuditor.setBackground(new Color(0, 102, 153));
    }//GEN-LAST:event_navAuditorMouseEntered

    private void navAuditorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navAuditorMouseExited
        // TODO add your handling code here:
        navAuditor.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        navAuditor.setBackground(new Color(0, 51, 102));
    }//GEN-LAST:event_navAuditorMouseExited

    private void navInfoKlienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navInfoKlienMouseClicked
        // TODO add your handling code here:
        InformasiKlien ik = new InformasiKlien();
        close();

        ik.show();
    }//GEN-LAST:event_navInfoKlienMouseClicked

    private void navInfoKlienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navInfoKlienMouseEntered
        // TODO add your handling code here:
        navInfoKlien.setCursor(new Cursor(Cursor.HAND_CURSOR));
        navInfoKlien.setBackground(new Color(0, 102, 153));
    }//GEN-LAST:event_navInfoKlienMouseEntered

    private void navInfoKlienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navInfoKlienMouseExited
        // TODO add your handling code here:
        navInfoKlien.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        navInfoKlien.setBackground(new Color(0, 51, 102));
    }//GEN-LAST:event_navInfoKlienMouseExited

    private void navHasilAuditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navHasilAuditMouseClicked
        // TODO add your handling code here:
        LaporanHasilAudit lha = new LaporanHasilAudit();
        close();

        lha.show();
    }//GEN-LAST:event_navHasilAuditMouseClicked

    private void navHasilAuditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navHasilAuditMouseEntered
        // TODO add your handling code here:
        navHasilAudit.setCursor(new Cursor(Cursor.HAND_CURSOR));
        navHasilAudit.setBackground(new Color(0, 102, 153));
    }//GEN-LAST:event_navHasilAuditMouseEntered

    private void navHasilAuditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navHasilAuditMouseExited
        // TODO add your handling code here:
        navHasilAudit.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        navHasilAudit.setBackground(new Color(0, 51, 102));
    }//GEN-LAST:event_navHasilAuditMouseExited

    private void navLaporanKeuanganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navLaporanKeuanganMouseClicked
        // TODO add your handling code here:
        LaporanKeuangan lk = new LaporanKeuangan();
        close();
        
        lk.show();
    }//GEN-LAST:event_navLaporanKeuanganMouseClicked

    private void navLaporanKeuanganMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navLaporanKeuanganMouseEntered
        // TODO add your handling code here:
        navLaporanKeuangan.setCursor(new Cursor(Cursor.HAND_CURSOR));
        navLaporanKeuangan.setBackground(new Color(0, 102, 153));
    }//GEN-LAST:event_navLaporanKeuanganMouseEntered

    private void navLaporanKeuanganMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navLaporanKeuanganMouseExited
        // TODO add your handling code here:
        navLaporanKeuangan.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        navLaporanKeuangan.setBackground(new Color(0, 51, 102));
    }//GEN-LAST:event_navLaporanKeuanganMouseExited

    private void navAfiliatorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navAfiliatorMouseClicked
        // TODO add your handling code here:
        Afiliator af = new Afiliator();
        close();

        af.show();
    }//GEN-LAST:event_navAfiliatorMouseClicked

    private void navAfiliatorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navAfiliatorMouseEntered
        // TODO add your handling code here:
        navAfiliator.setCursor(new Cursor(Cursor.HAND_CURSOR));
        navAfiliator.setBackground(new Color(0, 102, 153));
    }//GEN-LAST:event_navAfiliatorMouseEntered

    private void navAfiliatorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navAfiliatorMouseExited
        // TODO add your handling code here:
        navAfiliator.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        navAfiliator.setBackground(new Color(0, 51, 102));
    }//GEN-LAST:event_navAfiliatorMouseExited

    private void navFileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navFileMouseClicked
        // TODO add your handling code here:
        File file = new File();
        close();

        file.show();
    }//GEN-LAST:event_navFileMouseClicked

    private void navFileMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navFileMouseEntered
        // TODO add your handling code here:
        navFile.setCursor(new Cursor(Cursor.HAND_CURSOR));
        navFile.setBackground(new Color(0, 102, 153));
    }//GEN-LAST:event_navFileMouseEntered

    private void navFileMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navFileMouseExited
        // TODO add your handling code here:
        navFile.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        navFile.setBackground(new Color(0, 51, 102));
    }//GEN-LAST:event_navFileMouseExited

    private void removeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBtnActionPerformed
        // TODO add your handling code here:
        String idKlien = idKlienTxt.getText();

        String sqlQuery = "DELETE FROM files WHERE ID_klien='" + idKlien + "'";

        try {
            pst = conn.prepareStatement(sqlQuery);
            idKlienTxt.setText("");
            noLaiTxt.setText("");
            laiTxt.setText("");
            neracaTxt.setText("");
            calkTxt.setText("");
            labarugiTxt.setText("");
            arusKasTxt.setText("");
            keteranganTxt.setText("");

            pst.executeUpdate();
            populateTable();
            JOptionPane.showMessageDialog(null, "Data Successfully Removed");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        boolean isEditing = false;

        updateBtn.setEnabled(isEditing);
        idKlienTxt.setEnabled(isEditing);
        noLaiTxt.setEnabled(isEditing);
        laiTxt.setEnabled(isEditing);
        neracaTxt.setEnabled(isEditing);
        calkTxt.setEnabled(isEditing);
        labarugiTxt.setEnabled(isEditing);
        arusKasTxt.setEnabled(isEditing);
        keteranganTxt.setEnabled(isEditing);
    }//GEN-LAST:event_removeBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        String idKlien = idKlienTxt.getText();
        String noLai = noLaiTxt.getText();
        String fileLai = laiTxt.getText();
        String fileNeraca = neracaTxt.getText();
        String fileCalk = calkTxt.getText();
        String fileLabaRugi = labarugiTxt.getText();
        String fileArusKas = arusKasTxt.getText();
        String fileKeterangan = keteranganTxt.getText();

        String sqlQuery = "UPDATE files SET file_LAI=?, file_neraca=?, file_calk=?, file_labarugi=?, file_arus_kas=?, file_keterangan=? WHERE ID_Klien=?";

        try {
            pst = conn.prepareStatement(sqlQuery);
            pst.setString(1, fileLai);
            pst.setString(2, fileNeraca);
            pst.setString(3, fileCalk);
            pst.setString(4, fileLabaRugi);
            pst.setString(5, fileArusKas);
            pst.setString(6, fileKeterangan);
            pst.setString(7, idKlien);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Data Successfully Updated");
            populateTable(); // Assuming this method updates the UI table
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        isEditing = false;

    }//GEN-LAST:event_updateBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        String idKlien = idKlienTxt.getText();
        String noLai = noLaiTxt.getText();
        String fileLai = laiTxt.getText();
        String fileNeraca = neracaTxt.getText();
        String fileCalk = calkTxt.getText();
        String fileLabaRugi = labarugiTxt.getText();
        String fileArusKas = arusKasTxt.getText();
        String fileKeterangan = keteranganTxt.getText();

        String sqlQuery = "INSERT INTO files (ID_klien, no_LAI, file_LAI, file_neraca, file_calk, file_labarugi, file_arus_kas, file_keterangan) VALUES "
                + "(?, ?, ?, ?, ?, ?, ?, ?)";

        try {
            pst = conn.prepareStatement(sqlQuery);
            pst.setString(1, idKlien);
            pst.setString(2, noLai);
            pst.setString(3, fileLai);
            pst.setString(4, fileNeraca);
            pst.setString(5, fileCalk);
            pst.setString(6, fileLabaRugi);
            pst.setString(7, fileArusKas);
            pst.setString(8, fileKeterangan);

            pst.execute();
            JOptionPane.showMessageDialog(null, "Data Added Successfully");
            populateTable();

            idKlienTxt.setText("");
            noLaiTxt.setText("");
            laiTxt.setText("");
            neracaTxt.setText("");
            calkTxt.setText("");
            labarugiTxt.setText("");
            arusKasTxt.setText("");
            keteranganTxt.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            idKlienTxt.setText("");
            noLaiTxt.setText("");
            laiTxt.setText("");
            neracaTxt.setText("");
            calkTxt.setText("");
            labarugiTxt.setText("");
            arusKasTxt.setText("");
            keteranganTxt.setText("");
        }
        isEditing = false;
        updateFields();
        updateButtons();
    }//GEN-LAST:event_saveBtnActionPerformed

    private void browseBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseBtn1ActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        java.io.File path = chooser.getCurrentDirectory();
        java.io.File f = chooser.getSelectedFile();
        String fileName = f.getName();
//        String fileName = f.getAbsolutePath();

        laiTxt.setText(fileName);
    }//GEN-LAST:event_browseBtn1ActionPerformed

    private void browseBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseBtn2ActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        java.io.File f = chooser.getSelectedFile();
        String fileName = f.getName();

        neracaTxt.setText(fileName);
    }//GEN-LAST:event_browseBtn2ActionPerformed

    private void browseBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseBtn3ActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        java.io.File f = chooser.getSelectedFile();
        String fileName = f.getName();

        calkTxt.setText(fileName);
    }//GEN-LAST:event_browseBtn3ActionPerformed

    private void browseBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseBtn4ActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        java.io.File f = chooser.getSelectedFile();
        String fileName = f.getName();

        labarugiTxt.setText(fileName);
    }//GEN-LAST:event_browseBtn4ActionPerformed

    private void browseBtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseBtn5ActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        java.io.File f = chooser.getSelectedFile();
        String fileName = f.getName();

        arusKasTxt.setText(fileName);
    }//GEN-LAST:event_browseBtn5ActionPerformed

    private void browseBtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseBtn6ActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        java.io.File f = chooser.getSelectedFile();
        String fileName = f.getName();

        keteranganTxt.setText(fileName);
    }//GEN-LAST:event_browseBtn6ActionPerformed

    private void searchTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTxtKeyTyped
        String key = searchTxt.getText();
        String sqlQuery = "SELECT * FROM files WHERE ID_klien LIKE '%" + key + "%'";

        try {
            pst = conn.prepareStatement(sqlQuery);
            rs = pst.executeQuery();
            fileTbl.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }        // TODO add your handling code here:

    }//GEN-LAST:event_searchTxtKeyTyped

    private void newBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newBtnActionPerformed
        // TODO add your handling code here:
        isEditing = true;
        updateFields();
        updateButtons();
        idKlienTxt.setText("");
        noLaiTxt.setText("");
        laiTxt.setText("");
        neracaTxt.setText("");
        calkTxt.setText("");
        labarugiTxt.setText("");
        arusKasTxt.setText("");
        keteranganTxt.setText("");
    }//GEN-LAST:event_newBtnActionPerformed

    private void fileTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fileTblMouseClicked
        // TODO add your handling code here:
        int r = fileTbl.getSelectedRow();
        String click = fileTbl.getModel().getValueAt(r, 0).toString();
        String sqlQuery = "SELECT * FROM files WHERE ID_klien='" + click + "'";

        try {
            pst = conn.prepareStatement(sqlQuery);
            rs = pst.executeQuery();

            if (rs.next()) {
                String idKlien = rs.getString(1);
                idKlienTxt.setText(idKlien);
                String noLai = rs.getString(2);
                noLaiTxt.setText(noLai);
                String fileLai = rs.getString(3);
                laiTxt.setText(fileLai);
                String fileNeraca = rs.getString(4);
                neracaTxt.setText(fileNeraca);
                String fileCalk = rs.getString(5);
                calkTxt.setText(fileCalk);
                String fileLabaRugi = rs.getString(6);
                labarugiTxt.setText(fileLabaRugi);
                String fileArusKas = rs.getString(7);
                arusKasTxt.setText(fileArusKas);
                String fileKeterangan = rs.getString(8);
                keteranganTxt.setText(fileKeterangan);

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        isEditing = true;
        updateBtn.setEnabled(true);
        idKlienTxt.setEnabled(isEditing);
        noLaiTxt.setEnabled(isEditing);
        laiTxt.setEnabled(isEditing);
        neracaTxt.setEnabled(isEditing);
        calkTxt.setEnabled(isEditing);
        labarugiTxt.setEnabled(isEditing);
        arusKasTxt.setEnabled(isEditing);
        keteranganTxt.setEnabled(isEditing);
        browseBtn1.setEnabled(isEditing);
        browseBtn2.setEnabled(isEditing);
        browseBtn3.setEnabled(isEditing);
        browseBtn4.setEnabled(isEditing);
        browseBtn5.setEnabled(isEditing);
        browseBtn6.setEnabled(isEditing);
    }//GEN-LAST:event_fileTblMouseClicked

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel19MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(File.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(File.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(File.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(File.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new File().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField arusKasTxt;
    private javax.swing.JButton browseBtn1;
    private javax.swing.JButton browseBtn2;
    private javax.swing.JButton browseBtn3;
    private javax.swing.JButton browseBtn4;
    private javax.swing.JButton browseBtn5;
    private javax.swing.JButton browseBtn6;
    private javax.swing.JTextField calkTxt;
    private javax.swing.JTable fileTbl;
    private javax.swing.JTextField idKlienTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField keteranganTxt;
    private javax.swing.JTextField labarugiTxt;
    private javax.swing.JTextField laiTxt;
    private javax.swing.JPanel navAfiliator;
    private javax.swing.JPanel navAuditor;
    private javax.swing.JPanel navFile;
    private javax.swing.JPanel navHasilAudit;
    private javax.swing.JPanel navInfoKlien;
    private javax.swing.JPanel navLaporanKeuangan;
    private javax.swing.JTextField neracaTxt;
    private javax.swing.JButton newBtn;
    private javax.swing.JTextField noLaiTxt;
    private javax.swing.JButton removeBtn;
    private javax.swing.JButton saveBtn;
    private javax.swing.JTextField searchTxt;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
