/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projectBasdat;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author ASUS
 */
public class LaporanHasilAudit extends javax.swing.JFrame {

    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    boolean isEditing;

    /**
     * Creates new form LaporanHasilAudit
     */
    public LaporanHasilAudit() {
        initComponents();
        conn = Koneksi.connectRb();
        initUI();
        populateTable();
        fillDate();
    }

    public void initUI() {
        isEditing = false;
        updateButtons();
        updateFields();
    }

    public void updateButtons() {
        saveBtn.setEnabled(isEditing);
        updateBtn.setEnabled(isEditing);
    }

    public void updateFields() {
        IDKlienTxt.setEnabled(isEditing);
        noLAITxt.setEnabled(isEditing);
        tglLAI.setEnabled(isEditing);
        tahunTxt.setEnabled(isEditing);
        goPublikCb.setEnabled(isEditing);
        opiniTxt.setEnabled(isEditing);
        periodeAwalTxt.setEnabled(isEditing);
        periodeAkhirTxt.setEnabled(isEditing);
        keteranganTxt.setEnabled(isEditing);
        restatementCb.setEnabled(isEditing);
        noRestatTxt.setEnabled(isEditing);
        namaApSebelumnya.setEnabled(isEditing);
        tahunAPTxt.setEnabled(isEditing);
    }

    private void populateTable() {
        String sqlQuery = "SELECT * FROM hasil_audit";

        try {
            pst = conn.prepareStatement(sqlQuery);
            rs = pst.executeQuery();
            laiTbl.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
        }
    }

    public void fillDate() {
        Date date = new Date();
        tglLAI.setDateFormatString("dd-MM-yyyy");
        tglLAI.setDate(date);
        periodeAwalTxt.setDateFormatString("dd-MM-yyyy");
        periodeAwalTxt.setDate(date);
        periodeAkhirTxt.setDateFormatString("dd-MM-yyyy");
        periodeAkhirTxt.setDate(date);

    }

    public void close() {
        WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        navAuditor = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        navInfoKlien = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        navHasilAudit = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        navLaporanKeuangan = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        navAfiliator = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        navFile = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        restatementCb = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        noLAITxt = new javax.swing.JTextField();
        noRestatTxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        keteranganTxt = new javax.swing.JTextArea();
        opiniTxt = new javax.swing.JTextField();
        goPublikCb = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        searchTxt = new javax.swing.JTextField();
        newBtn = new javax.swing.JButton();
        removeBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        cetakBtn = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        namaApSebelumnya = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        IDKlienTxt = new javax.swing.JTextField();
        tglLAI = new com.toedter.calendar.JDateChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        laiTbl = new javax.swing.JTable();
        periodeAwalTxt = new com.toedter.calendar.JDateChooser();
        periodeAkhirTxt = new com.toedter.calendar.JDateChooser();
        tahunTxt = new com.toedter.calendar.JYearChooser();
        tahunAPTxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));

        navAuditor.setBackground(new java.awt.Color(0, 51, 102));
        navAuditor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                navAuditorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                navAuditorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                navAuditorMouseExited(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Poppins Medium", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Tabel Auditor");

        javax.swing.GroupLayout navAuditorLayout = new javax.swing.GroupLayout(navAuditor);
        navAuditor.setLayout(navAuditorLayout);
        navAuditorLayout.setHorizontalGroup(
            navAuditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navAuditorLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        navAuditorLayout.setVerticalGroup(
            navAuditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navAuditorLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addContainerGap())
        );

        navInfoKlien.setBackground(new java.awt.Color(0, 51, 102));
        navInfoKlien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                navInfoKlienMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                navInfoKlienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                navInfoKlienMouseExited(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Poppins Medium", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Informasi Klien");

        javax.swing.GroupLayout navInfoKlienLayout = new javax.swing.GroupLayout(navInfoKlien);
        navInfoKlien.setLayout(navInfoKlienLayout);
        navInfoKlienLayout.setHorizontalGroup(
            navInfoKlienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(navInfoKlienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(navInfoKlienLayout.createSequentialGroup()
                    .addGap(0, 32, Short.MAX_VALUE)
                    .addComponent(jLabel17)
                    .addGap(0, 36, Short.MAX_VALUE)))
        );
        navInfoKlienLayout.setVerticalGroup(
            navInfoKlienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(navInfoKlienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(navInfoKlienLayout.createSequentialGroup()
                    .addGap(0, 11, Short.MAX_VALUE)
                    .addComponent(jLabel17)
                    .addGap(0, 11, Short.MAX_VALUE)))
        );

        navHasilAudit.setBackground(new java.awt.Color(0, 102, 153));
        navHasilAudit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                navHasilAuditMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                navHasilAuditMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                navHasilAuditMouseExited(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Poppins Medium", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Laporan Hasil Audit");

        javax.swing.GroupLayout navHasilAuditLayout = new javax.swing.GroupLayout(navHasilAudit);
        navHasilAudit.setLayout(navHasilAuditLayout);
        navHasilAuditLayout.setHorizontalGroup(
            navHasilAuditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navHasilAuditLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel16)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        navHasilAuditLayout.setVerticalGroup(
            navHasilAuditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navHasilAuditLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        navLaporanKeuangan.setBackground(new java.awt.Color(0, 51, 102));
        navLaporanKeuangan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                navLaporanKeuanganMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                navLaporanKeuanganMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                navLaporanKeuanganMouseExited(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Poppins Medium", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Laporan Keuangan ");

        javax.swing.GroupLayout navLaporanKeuanganLayout = new javax.swing.GroupLayout(navLaporanKeuangan);
        navLaporanKeuangan.setLayout(navLaporanKeuanganLayout);
        navLaporanKeuanganLayout.setHorizontalGroup(
            navLaporanKeuanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navLaporanKeuanganLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addGap(18, 18, 18))
        );
        navLaporanKeuanganLayout.setVerticalGroup(
            navLaporanKeuanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navLaporanKeuanganLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addContainerGap())
        );

        navAfiliator.setBackground(new java.awt.Color(0, 51, 102));
        navAfiliator.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                navAfiliatorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                navAfiliatorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                navAfiliatorMouseExited(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Poppins Medium", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Afiliator");

        javax.swing.GroupLayout navAfiliatorLayout = new javax.swing.GroupLayout(navAfiliator);
        navAfiliator.setLayout(navAfiliatorLayout);
        navAfiliatorLayout.setHorizontalGroup(
            navAfiliatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navAfiliatorLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel20)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        navAfiliatorLayout.setVerticalGroup(
            navAfiliatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navAfiliatorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addContainerGap())
        );

        navFile.setBackground(new java.awt.Color(0, 51, 102));
        navFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                navFileMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                navFileMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                navFileMouseExited(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Poppins Medium", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("File ");

        javax.swing.GroupLayout navFileLayout = new javax.swing.GroupLayout(navFile);
        navFile.setLayout(navFileLayout);
        navFileLayout.setHorizontalGroup(
            navFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navFileLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jLabel22)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        navFileLayout.setVerticalGroup(
            navFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navFileLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Poppins", 3, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("AM");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(navAuditor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(navInfoKlien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(navHasilAudit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(navLaporanKeuangan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(navAfiliator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(navFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel4)
                .addGap(31, 31, 31)
                .addComponent(navInfoKlien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(navAuditor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(navHasilAudit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(navLaporanKeuangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(navAfiliator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(navFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(262, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel1.setText("No. LAI");

        jLabel2.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel2.setText("Tgl. LAI");

        jLabel3.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel3.setText("Tahun Takwim");

        jLabel5.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel5.setText("Restatement");

        restatementCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ya", "Tidak" }));

        jLabel6.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel6.setText("No. LAI Restatement");

        jLabel7.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel7.setText("Go Publik");

        jLabel8.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel8.setText("Opini");

        jLabel9.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel9.setText("Periode Awal");

        jLabel10.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel10.setText("Periode Akhir");

        jLabel11.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel11.setText("Keterangan");

        keteranganTxt.setColumns(20);
        keteranganTxt.setRows(5);
        jScrollPane1.setViewportView(keteranganTxt);

        goPublikCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ya", "Tidak" }));

        jLabel18.setFont(new java.awt.Font("Poppins", 1, 36)); // NOI18N
        jLabel18.setText("LAPORAN HASIL AUDIT");

        jLabel14.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel14.setText("Search by No. LAI");

        searchTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTxtActionPerformed(evt);
            }
        });
        searchTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchTxtKeyTyped(evt);
            }
        });

        newBtn.setText("New");
        newBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newBtnActionPerformed(evt);
            }
        });

        removeBtn.setText("Remove");
        removeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBtnActionPerformed(evt);
            }
        });

        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        cetakBtn.setText("Cetak");
        cetakBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cetakBtnActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel12.setText("Nama AP sebelumnya");

        jLabel13.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel13.setText("Tahun AP sebelum");

        jLabel23.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel23.setText("ID Klien");

        laiTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Klien", "No. LAI", "Tgl. LAI", "Tahun Takwi,", "Go Publik", "Opini", "Periode Awal", "Periode Akhir", "Restatement", "No. LAI Restatement", "AP Sebelumnya", "Tahun AP Sebelumnya", "Keterangan"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        laiTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                laiTblMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(laiTbl);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(newBtn)
                        .addGap(18, 18, 18)
                        .addComponent(removeBtn)
                        .addGap(18, 18, 18)
                        .addComponent(updateBtn)
                        .addGap(18, 18, 18)
                        .addComponent(saveBtn)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel14)
                                    .addGap(68, 68, 68)
                                    .addComponent(searchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(521, 521, 521)
                                    .addComponent(cetakBtn))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 947, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(264, 264, 264)
                                .addComponent(jLabel18))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(IDKlienTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                                    .addComponent(noLAITxt, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                                    .addComponent(tglLAI, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                                    .addComponent(tahunTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(42, 42, 42)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(opiniTxt)
                                            .addComponent(goPublikCb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(periodeAwalTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(periodeAkhirTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(noRestatTxt)
                                    .addComponent(namaApSebelumnya)
                                    .addComponent(restatementCb, 0, 146, Short.MAX_VALUE)
                                    .addComponent(tahunAPTxt))))
                        .addContainerGap(173, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel23)
                            .addComponent(IDKlienTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tglLAI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(noLAITxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(tahunTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(goPublikCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(opiniTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(periodeAwalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10)
                                    .addComponent(periodeAkhirTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(restatementCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(noRestatTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(namaApSebelumnya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(tahunAPTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newBtn)
                    .addComponent(removeBtn)
                    .addComponent(updateBtn)
                    .addComponent(saveBtn))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(cetakBtn))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void navAuditorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navAuditorMouseClicked
        // TODO add your handling code here:
        FormAuditor fa = new FormAuditor();
        close();

        fa.show();
    }//GEN-LAST:event_navAuditorMouseClicked

    private void navAuditorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navAuditorMouseEntered
        // TODO add your handling code here:
        navAuditor.setCursor(new Cursor(Cursor.HAND_CURSOR));
        navAuditor.setBackground(new Color(0, 102, 153));
    }//GEN-LAST:event_navAuditorMouseEntered

    private void navAuditorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navAuditorMouseExited
        // TODO add your handling code here:
        navAuditor.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        navAuditor.setBackground(new Color(0, 51, 102));

    }//GEN-LAST:event_navAuditorMouseExited

    private void navInfoKlienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navInfoKlienMouseClicked
        // TODO add your handling code here:
        InformasiKlien ik = new InformasiKlien();
        close();

        ik.show();
    }//GEN-LAST:event_navInfoKlienMouseClicked

    private void navInfoKlienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navInfoKlienMouseEntered
        // TODO add your handling code here:
        navInfoKlien.setCursor(new Cursor(Cursor.HAND_CURSOR));
        navInfoKlien.setBackground(new Color(0, 102, 153));
    }//GEN-LAST:event_navInfoKlienMouseEntered

    private void navInfoKlienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navInfoKlienMouseExited
        // TODO add your handling code here:
        navInfoKlien.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        navInfoKlien.setBackground(new Color(0, 51, 102));
    }//GEN-LAST:event_navInfoKlienMouseExited

    private void navHasilAuditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navHasilAuditMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_navHasilAuditMouseClicked

    private void navHasilAuditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navHasilAuditMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_navHasilAuditMouseEntered

    private void navHasilAuditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navHasilAuditMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_navHasilAuditMouseExited

    private void searchTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTxtKeyTyped
        // TODO add your handling code here:
        String key = searchTxt.getText();
        String sqlQuery = "SELECT * FROM hasil_audit WHERE no_LAI LIKE '%" + key + "%'";

        try {
            pst = conn.prepareStatement(sqlQuery);
            rs = pst.executeQuery();
            laiTbl.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_searchTxtKeyTyped

    private void searchTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchTxtActionPerformed

    private void removeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBtnActionPerformed
        // TODO add your handling code here:
        String noLAI = noLAITxt.getText();

        String sqlQuery = "DELETE FROM hasil_audit WHERE no_LAI='" + noLAI + "'";

        try {
            IDKlienTxt.setText("");
            noLAITxt.setText("");
            tglLAI.setDate(null);
            tahunTxt.setYear(2023);
            goPublikCb.setSelectedIndex(0);
            opiniTxt.setText("");
            periodeAwalTxt.setDate(null);
            periodeAkhirTxt.setDate(null);
            keteranganTxt.setText("");
            restatementCb.setSelectedIndex(0);
            noRestatTxt.setText("");
            namaApSebelumnya.setText("");
            tahunAPTxt.setText("");
            pst = conn.prepareStatement(sqlQuery);
            pst.execute();
            populateTable();
            JOptionPane.showMessageDialog(null, "Data Successfully Removed");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

        boolean isEditing = false;

        IDKlienTxt.setEnabled(isEditing);
        noLAITxt.setEnabled(isEditing);
        tglLAI.setEnabled(isEditing);
        tahunTxt.setEnabled(isEditing);
        goPublikCb.setEnabled(isEditing);
        opiniTxt.setEnabled(isEditing);
        periodeAwalTxt.setEnabled(isEditing);
        periodeAkhirTxt.setEnabled(isEditing);
        keteranganTxt.setEnabled(isEditing);
        restatementCb.setEnabled(isEditing);
        noRestatTxt.setEnabled(isEditing);
        namaApSebelumnya.setEnabled(isEditing);
        tahunAPTxt.setEnabled(isEditing);

    }//GEN-LAST:event_removeBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        String idKlienValue = IDKlienTxt.getText();
        String noLAIValue = noLAITxt.getText();
        Date tglLAIValue = tglLAI.getDate();
        int tahunTakwim = tahunTxt.getYear();
        String goPublikIndex = (String) goPublikCb.getSelectedItem();
        String opiniValue = opiniTxt.getText();
        Date periodeAwalValue = periodeAwalTxt.getDate();
        Date periodeAkhirValue = periodeAkhirTxt.getDate();
        String keteranganValue = keteranganTxt.getText();
        String restatementIndex = (String) restatementCb.getSelectedItem();
        String noRestatValue = noRestatTxt.getText();
        String namaApSebelumValue = namaApSebelumnya.getText();
        String tahunAPValue = tahunAPTxt.getText();
        

        String sqlQuery = "UPDATE hasil_audit SET ID_klien=?, tgl_LAI=?, tahun_takwim=?, go_publik=?, opini=?, periode_awal=?, periode_akhir=?, restatement=?, no_restatement=?, nama_ap_sebelumnya=?, tahun_ap_sebelumnya=?, keterangan=? WHERE no_LAI=?";

        try {
            pst = conn.prepareStatement(sqlQuery);
            pst.setString(1, idKlienValue);
            pst.setDate(2, new java.sql.Date(tglLAIValue.getTime()));
            pst.setInt(3, tahunTakwim);
            pst.setString(4, goPublikIndex);
            pst.setString(5, opiniValue);
            pst.setDate(6, new java.sql.Date(periodeAwalValue.getTime()));
            pst.setDate(7, new java.sql.Date(periodeAkhirValue.getTime()));
            pst.setString(8, restatementIndex);
            pst.setString(9, noRestatValue);
            pst.setString(10, namaApSebelumValue);
            pst.setString(11, (tahunAPValue.isEmpty() ? "" : tahunAPValue));
            pst.setString(12, keteranganValue);
            pst.setString(13, noLAIValue);

            pst.execute();
            populateTable();
            JOptionPane.showMessageDialog(null, "Data Successfully Updated");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

        isEditing = false;
        updateFields();
        updateButtons();


    }//GEN-LAST:event_updateBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        String idKlienValue = IDKlienTxt.getText();
        String noLAIValue = noLAITxt.getText();
        Date tglLAIValue = tglLAI.getDate();
        int tahunTakwim = tahunTxt.getYear();
        String goPublikIndex = (String) goPublikCb.getSelectedItem();
        String opiniValue = opiniTxt.getText();
        Date periodeAwalValue = periodeAwalTxt.getDate();
        Date periodeAkhirValue = periodeAkhirTxt.getDate();
        String keteranganValue = keteranganTxt.getText();
        String restatementIndex = (String) restatementCb.getSelectedItem();
        String noRestatValue = noRestatTxt.getText();
        String namaApSebelumValue = namaApSebelumnya.getText();
        String tahunAPValue = tahunAPTxt.getText();

        String sqlQuery = "INSERT INTO hasil_audit (ID_klien, no_LAI, tgl_LAI, tahun_takwim, go_publik, opini, periode_awal, periode_akhir, restatement, no_restatement, nama_ap_sebelumnya, tahun_ap_sebelumnya, keterangan) VALUES "
                + "(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

        try {
            pst = conn.prepareStatement(sqlQuery);
            pst.setString(1, idKlienValue);
            pst.setString(2, noLAIValue);
            pst.setDate(3, new java.sql.Date(tglLAIValue.getTime()));
            pst.setInt(4, tahunTakwim);
            pst.setString(5, goPublikIndex);
            pst.setString(6, opiniValue);
            pst.setDate(7, new java.sql.Date(periodeAwalValue.getTime()));
            pst.setDate(8, new java.sql.Date(periodeAkhirValue.getTime()));
            pst.setString(9, restatementIndex);
            pst.setString(10, noRestatValue);
            pst.setString(11, namaApSebelumValue);
            pst.setString(12, (tahunAPValue.isEmpty() ? "" : tahunAPValue));
            pst.setString(13, keteranganValue);

            pst.execute();
            JOptionPane.showMessageDialog(null, "Data Added Successfully");
            populateTable();

            IDKlienTxt.setText("");
            noLAITxt.setText("");
            tglLAI.setDate(null);
            tahunTxt.setYear(2023);
            goPublikCb.setSelectedIndex(0);
            opiniTxt.setText("");
            periodeAwalTxt.setDate(null);
            periodeAkhirTxt.setDate(null);
            keteranganTxt.setText("");
            restatementCb.setSelectedIndex(0);
            noRestatTxt.setText("");
            namaApSebelumnya.setText("");
            tahunAPTxt.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            IDKlienTxt.setText("");
            noLAITxt.setText("");
            tglLAI.setDate(null);
            tahunTxt.setYear(2023);
            goPublikCb.setSelectedIndex(0);
            opiniTxt.setText("");
            periodeAwalTxt.setDate(null);
            periodeAkhirTxt.setDate(null);
            keteranganTxt.setText("");
            restatementCb.setSelectedIndex(0);
            noRestatTxt.setText("");
            namaApSebelumnya.setText("");
            tahunAPTxt.setText("");
        }
        isEditing = false;
        updateFields();
        updateButtons();
    }//GEN-LAST:event_saveBtnActionPerformed

    private void navLaporanKeuanganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navLaporanKeuanganMouseClicked
        // TODO add your handling code here:
        LaporanKeuangan lk = new LaporanKeuangan();
        close();

        lk.show();
    }//GEN-LAST:event_navLaporanKeuanganMouseClicked

    private void navLaporanKeuanganMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navLaporanKeuanganMouseEntered
        // TODO add your handling code here:
        navLaporanKeuangan.setCursor(new Cursor(Cursor.HAND_CURSOR));
        navLaporanKeuangan.setBackground(new Color(0, 102, 153));
    }//GEN-LAST:event_navLaporanKeuanganMouseEntered

    private void navLaporanKeuanganMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navLaporanKeuanganMouseExited
        // TODO add your handling code here:
        navLaporanKeuangan.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        navLaporanKeuangan.setBackground(new Color(0, 51, 102));
    }//GEN-LAST:event_navLaporanKeuanganMouseExited

    private void navAfiliatorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navAfiliatorMouseClicked
        // TODO add your handling code here:
        Afiliator af = new Afiliator();
        close();

        af.show();
    }//GEN-LAST:event_navAfiliatorMouseClicked

    private void navAfiliatorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navAfiliatorMouseEntered
        // TODO add your handling code here:
        navAfiliator.setCursor(new Cursor(Cursor.HAND_CURSOR));
        navAfiliator.setBackground(new Color(0, 102, 153));
    }//GEN-LAST:event_navAfiliatorMouseEntered

    private void navAfiliatorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navAfiliatorMouseExited
        // TODO add your handling code here:
        navAfiliator.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        navAfiliator.setBackground(new Color(0, 51, 102));
    }//GEN-LAST:event_navAfiliatorMouseExited

    private void navFileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navFileMouseClicked
        // TODO add your handling code here:
        File file = new File();
        close();

        file.show();
    }//GEN-LAST:event_navFileMouseClicked

    private void navFileMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navFileMouseEntered
        // TODO add your handling code here:
        navFile.setCursor(new Cursor(Cursor.HAND_CURSOR));
        navFile.setBackground(new Color(0, 102, 153));
    }//GEN-LAST:event_navFileMouseEntered

    private void navFileMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navFileMouseExited
        // TODO add your handling code here:
        navFile.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        navFile.setBackground(new Color(0, 51, 102));
    }//GEN-LAST:event_navFileMouseExited

    private void newBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newBtnActionPerformed
        // TODO add your handling code here:
        isEditing = true;
        updateFields();
        updateButtons();
        IDKlienTxt.setText("");
        noLAITxt.setText("");
        tglLAI.setDate(null);
        tahunTxt.setYear(2023);
        goPublikCb.setSelectedIndex(0);
        opiniTxt.setText("");
        periodeAwalTxt.setDate(null);
        periodeAkhirTxt.setDate(null);
        keteranganTxt.setText("");
        restatementCb.setSelectedIndex(0);
        noRestatTxt.setText("");
        namaApSebelumnya.setText("");
        tahunAPTxt.setText("");
    }//GEN-LAST:event_newBtnActionPerformed

    private void laiTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laiTblMouseClicked
        // TODO add your handling code here:
        int r = laiTbl.getSelectedRow();
        String click = laiTbl.getModel().getValueAt(r, 1).toString();
        String sqlQuery = "SELECT * FROM hasil_audit WHERE no_LAI='" + click + "'";

        try {
            pst = conn.prepareStatement(sqlQuery);
            rs = pst.executeQuery();

            if (rs.next()) {
                String idKlienValue = rs.getString(1);
                IDKlienTxt.setText(idKlienValue);
                String noLAIValue = rs.getString(2);
                noLAITxt.setText(noLAIValue);
                Date tglLAIValue = rs.getDate(3);
                tglLAI.setDate(tglLAIValue);
                int tahunTakwimValue = rs.getInt(4);
                tahunTxt.setYear(tahunTakwimValue);
                String goPublikIndex = rs.getString(5);
                goPublikCb.setSelectedItem(goPublikIndex);
                String opiniValue = rs.getString(6);
                opiniTxt.setText(opiniValue);
                Date periodeAwalValue = rs.getDate(7);
                periodeAwalTxt.setDate(periodeAwalValue);
                Date periodeAkhirValue = rs.getDate(8);
                periodeAkhirTxt.setDate(periodeAkhirValue);
                String restatementIndexValue = rs.getString(9);
                restatementCb.setSelectedItem(restatementIndexValue);
                String noRestatValue = rs.getString(10);
                noRestatTxt.setText(noRestatValue);
                String IdApSebelumValue = rs.getString(11);
                namaApSebelumnya.setText(IdApSebelumValue);
                String tahunAPValue = rs.getString(12);
                tahunAPTxt.setText(tahunAPValue);
                String keteranganValue = rs.getString(13);
                keteranganTxt.setText(keteranganValue);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

        isEditing = true;
        IDKlienTxt.setEnabled(isEditing);
        noLAITxt.setEnabled(isEditing);
        tglLAI.setEnabled(isEditing);
        tahunTxt.setEnabled(isEditing);
        goPublikCb.setEnabled(isEditing);
        opiniTxt.setEnabled(isEditing);
        periodeAwalTxt.setEnabled(isEditing);
        periodeAkhirTxt.setEnabled(isEditing);
        keteranganTxt.setEnabled(isEditing);
        restatementCb.setEnabled(isEditing);
        noRestatTxt.setEnabled(isEditing);
        namaApSebelumnya.setEnabled(isEditing);
        tahunAPTxt.setEnabled(isEditing);
        updateBtn.setEnabled(true);
    }//GEN-LAST:event_laiTblMouseClicked

    private void cetakBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cetakBtnActionPerformed
        // TODO add your handling code here:
        try {
            
            String reportPath = "D:\\KULIAH\\SEMESTER 3\\BASDAT\\PROJECT AKHIR\\projectAkhir\\Jasperreports\\hasil_audit.jrxml";
            JasperReport jr = JasperCompileManager.compileReport(reportPath);
            JasperPrint jp = JasperFillManager.fillReport(jr, null, conn);
            JasperViewer.viewReport(jp);
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_cetakBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LaporanHasilAudit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LaporanHasilAudit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LaporanHasilAudit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LaporanHasilAudit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LaporanHasilAudit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IDKlienTxt;
    private javax.swing.JButton cetakBtn;
    private javax.swing.JComboBox<String> goPublikCb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea keteranganTxt;
    private javax.swing.JTable laiTbl;
    private javax.swing.JTextField namaApSebelumnya;
    private javax.swing.JPanel navAfiliator;
    private javax.swing.JPanel navAuditor;
    private javax.swing.JPanel navFile;
    private javax.swing.JPanel navHasilAudit;
    private javax.swing.JPanel navInfoKlien;
    private javax.swing.JPanel navLaporanKeuangan;
    private javax.swing.JButton newBtn;
    private javax.swing.JTextField noLAITxt;
    private javax.swing.JTextField noRestatTxt;
    private javax.swing.JTextField opiniTxt;
    private com.toedter.calendar.JDateChooser periodeAkhirTxt;
    private com.toedter.calendar.JDateChooser periodeAwalTxt;
    private javax.swing.JButton removeBtn;
    private javax.swing.JComboBox<String> restatementCb;
    private javax.swing.JButton saveBtn;
    private javax.swing.JTextField searchTxt;
    private javax.swing.JTextField tahunAPTxt;
    private com.toedter.calendar.JYearChooser tahunTxt;
    private com.toedter.calendar.JDateChooser tglLAI;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
