/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projectBasdat;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author ASUS
 */
public class FormAuditor extends javax.swing.JFrame {
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    boolean isEditing;

    /**
     * Creates new form FormAuditor
     */
    public FormAuditor() {
        initComponents();
        initUI();
        conn = Koneksi.connectRb();
        populateTable();
    }
    
    public void initUI() {
        isEditing = false;
        updateButtons();
        updateFields();
    }
    
    public void updateButtons() {
        saveBtn.setEnabled(isEditing);
        updateBtn.setEnabled(isEditing);
    }

    public void updateFields() {
        noIDTxt.setEnabled(isEditing);
        namaTxt.setEnabled(isEditing);
        alamatTxt.setEnabled(isEditing);
        gajiSpn.setEnabled(isEditing);
    }
    
    private void populateTable() {
        String sqlQuery = "SELECT * FROM auditor";
        
        try {
            pst = conn.prepareStatement(sqlQuery);
            rs = pst.executeQuery();
            auditorTbl.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
        }
    }
    
    public void close() {
        WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        noIDTxt = new javax.swing.JTextField();
        namaTxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        auditorTbl = new javax.swing.JTable();
        saveBtn = new javax.swing.JButton();
        newBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        removeBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        navInfoKlien = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        navAuditor = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        navHasilAudit = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        navFile = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        navLaporanKeuangan = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        navAfiliator = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        searchTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cetakBtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        alamatTxt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        gajiSpn = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Poppins", 1, 36)); // NOI18N
        jLabel1.setText("AUDITOR");

        jLabel2.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel2.setText("No. Identitas");

        jLabel3.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel3.setText("Nama");

        auditorTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No. Identitas", "Nama", "Alamat", "Gaji"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        auditorTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                auditorTblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(auditorTbl);

        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        newBtn.setText("New");
        newBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newBtnActionPerformed(evt);
            }
        });

        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        removeBtn.setText("Remove");
        removeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBtnActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));

        jLabel4.setFont(new java.awt.Font("Poppins", 3, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("AM");

        navInfoKlien.setBackground(new java.awt.Color(0, 51, 102));
        navInfoKlien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                navInfoKlienMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                navInfoKlienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                navInfoKlienMouseExited(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Poppins Medium", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Informasi Klien");

        javax.swing.GroupLayout navInfoKlienLayout = new javax.swing.GroupLayout(navInfoKlien);
        navInfoKlien.setLayout(navInfoKlienLayout);
        navInfoKlienLayout.setHorizontalGroup(
            navInfoKlienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(navInfoKlienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(navInfoKlienLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel6)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        navInfoKlienLayout.setVerticalGroup(
            navInfoKlienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(navInfoKlienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(navInfoKlienLayout.createSequentialGroup()
                    .addGap(0, 11, Short.MAX_VALUE)
                    .addComponent(jLabel6)
                    .addGap(0, 11, Short.MAX_VALUE)))
        );

        navAuditor.setBackground(new java.awt.Color(0, 102, 153));
        navAuditor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                navAuditorMouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Poppins Medium", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Tabel Auditor");

        javax.swing.GroupLayout navAuditorLayout = new javax.swing.GroupLayout(navAuditor);
        navAuditor.setLayout(navAuditorLayout);
        navAuditorLayout.setHorizontalGroup(
            navAuditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(navAuditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(navAuditorLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel8)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        navAuditorLayout.setVerticalGroup(
            navAuditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
            .addGroup(navAuditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(navAuditorLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel8)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        navHasilAudit.setBackground(new java.awt.Color(0, 51, 102));
        navHasilAudit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                navHasilAuditMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                navHasilAuditMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                navHasilAuditMouseExited(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Poppins Medium", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Laporan Hasil Audit");

        javax.swing.GroupLayout navHasilAuditLayout = new javax.swing.GroupLayout(navHasilAudit);
        navHasilAudit.setLayout(navHasilAuditLayout);
        navHasilAuditLayout.setHorizontalGroup(
            navHasilAuditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navHasilAuditLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel19)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        navHasilAuditLayout.setVerticalGroup(
            navHasilAuditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navHasilAuditLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        navFile.setBackground(new java.awt.Color(0, 51, 102));
        navFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                navFileMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                navFileMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                navFileMouseExited(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Poppins Medium", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("File ");

        javax.swing.GroupLayout navFileLayout = new javax.swing.GroupLayout(navFile);
        navFile.setLayout(navFileLayout);
        navFileLayout.setHorizontalGroup(
            navFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navFileLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jLabel22)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        navFileLayout.setVerticalGroup(
            navFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navFileLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        navLaporanKeuangan.setBackground(new java.awt.Color(0, 51, 102));
        navLaporanKeuangan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                navLaporanKeuanganMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                navLaporanKeuanganMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                navLaporanKeuanganMouseExited(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Poppins Medium", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Laporan Keuangan ");

        javax.swing.GroupLayout navLaporanKeuanganLayout = new javax.swing.GroupLayout(navLaporanKeuangan);
        navLaporanKeuangan.setLayout(navLaporanKeuanganLayout);
        navLaporanKeuanganLayout.setHorizontalGroup(
            navLaporanKeuanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navLaporanKeuanganLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addGap(18, 18, 18))
        );
        navLaporanKeuanganLayout.setVerticalGroup(
            navLaporanKeuanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navLaporanKeuanganLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addContainerGap())
        );

        navAfiliator.setBackground(new java.awt.Color(0, 51, 102));
        navAfiliator.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                navAfiliatorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                navAfiliatorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                navAfiliatorMouseExited(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Poppins Medium", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Afiliator");

        javax.swing.GroupLayout navAfiliatorLayout = new javax.swing.GroupLayout(navAfiliator);
        navAfiliator.setLayout(navAfiliatorLayout);
        navAfiliatorLayout.setHorizontalGroup(
            navAfiliatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navAfiliatorLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel21)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        navAfiliatorLayout.setVerticalGroup(
            navAfiliatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navAfiliatorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel21)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(navInfoKlien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(navAuditor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(navHasilAudit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(navLaporanKeuangan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(navAfiliator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(navFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel4)
                .addGap(28, 28, 28)
                .addComponent(navInfoKlien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(navAuditor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(navHasilAudit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(navLaporanKeuangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(navAfiliator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(navFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(197, Short.MAX_VALUE))
        );

        searchTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTxtActionPerformed(evt);
            }
        });
        searchTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchTxtKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel5.setText("Search by Nama");

        cetakBtn.setText("Cetak");
        cetakBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cetakBtnActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel9.setText("Alamat");

        jLabel10.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel10.setText("Gaji");

        gajiSpn.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 10000));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(367, 367, 367)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(searchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 715, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cetakBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(newBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23)
                                .addComponent(removeBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(342, 342, 342)
                                .addComponent(updateBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(saveBtn))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(126, 126, 126)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(noIDTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                                        .addComponent(namaTxt)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(126, 126, 126)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(alamatTxt)
                                        .addComponent(gajiSpn)))))))
                .addContainerGap(145, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(noIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(alamatTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(gajiSpn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newBtn)
                    .addComponent(saveBtn)
                    .addComponent(updateBtn)
                    .addComponent(removeBtn))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(searchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cetakBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        String noIdentitas = noIDTxt.getText();
        String nama = namaTxt.getText();
        String alamat = alamatTxt.getText();
        int gaji = (int) gajiSpn.getValue();
        String sqlQuery = "INSERT INTO auditor (no_auditor, nama, alamat, gaji) VALUES"
        + "('" + noIdentitas + "','" + nama + "','" + alamat + "'," + gaji + ");";
        
        try {
            pst = conn.prepareStatement(sqlQuery);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Data Added Successfully");
            populateTable();
            noIDTxt.setText("");
            namaTxt.setText("");
            alamatTxt.setText("");
            gajiSpn.setValue(0);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            noIDTxt.setText("");
            namaTxt.setText("");
            alamatTxt.setText("");
            gajiSpn.setValue(0);
        }
        
        isEditing = false;
        updateFields();
        updateButtons();
    }//GEN-LAST:event_saveBtnActionPerformed

    private void auditorTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_auditorTblMouseClicked
        // TODO add your handling code here:
        int r = auditorTbl.getSelectedRow();
        String click = auditorTbl.getModel().getValueAt(r, 0).toString();
        String sqlQuery = "SELECT * FROM auditor WHERE no_auditor='" + click + "'";
        
        try {
            pst = conn.prepareStatement(sqlQuery);
            rs = pst.executeQuery();
            if (rs.next()) {
                String noIdentitas = rs.getString(1);
                noIDTxt.setText(noIdentitas);
                String nama = rs.getString(2);
                namaTxt.setText(nama);
                String alamat = rs.getString(3);
                alamatTxt.setText(alamat);
                int gaji = rs.getInt(4);
                gajiSpn.setValue(gaji);
                
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
        noIDTxt.setEnabled(true);
        namaTxt.setEnabled(true);
        alamatTxt.setEnabled(true);
        gajiSpn.setEnabled(true);
        updateBtn.setEnabled(true);

    }//GEN-LAST:event_auditorTblMouseClicked

    private void newBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newBtnActionPerformed
        // TODO add your handling code here:
        isEditing = true;
        updateFields();
        updateButtons();
        noIDTxt.setText("");
        namaTxt.setText("");
        alamatTxt.setText("");
        gajiSpn.setValue(0);
    }//GEN-LAST:event_newBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        String noIdentitas = noIDTxt.getText();
        String nama = namaTxt.getText();
        String alamat = alamatTxt.getText();
        int gaji = (int) gajiSpn.getValue();

        String sqlQuery = "UPDATE auditor SET nama=?, alamat=?, gaji=? WHERE no_auditor=" + "'" + noIdentitas+ "'";
        try {
            pst = conn.prepareStatement(sqlQuery);
            pst.setString(1, nama);
            pst.setString(2, alamat);
            pst.setInt(3, gaji);
            pst.execute();
            populateTable();
            JOptionPane.showMessageDialog(null, "Data Successfully Updated");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

        isEditing = false;
        updateFields();
        updateButtons();
    }//GEN-LAST:event_updateBtnActionPerformed

    private void removeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBtnActionPerformed
        // TODO add your handling code here:
        String noIdentitas = noIDTxt.getText();

        String sqlQuery = "DELETE FROM auditor WHERE no_auditor='" + noIdentitas + "'";

        try {
            noIDTxt.setText("");
            namaTxt.setText("");
            pst = conn.prepareStatement(sqlQuery);
            pst.execute();
            populateTable();
            JOptionPane.showMessageDialog(null, "Data Successfully Removed");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
        noIDTxt.setEnabled(false);
        namaTxt.setEnabled(false);
        gajiSpn.setEnabled(false);
        alamatTxt.setEnabled(false);
    }//GEN-LAST:event_removeBtnActionPerformed

    private void searchTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTxtKeyTyped
        // TODO add your handling code here:
        String key = searchTxt.getText();
        String sqlQuery = "SELECT * FROM auditor WHERE nama LIKE '%"+key+"%'";
        
        try {
            pst = conn.prepareStatement(sqlQuery);
            rs = pst.executeQuery();
            auditorTbl.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_searchTxtKeyTyped

    private void navInfoKlienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navInfoKlienMouseClicked
        // TODO add your handling code here:
        InformasiKlien ik = new InformasiKlien();
        close();
        
        ik.show();
        
    }//GEN-LAST:event_navInfoKlienMouseClicked

    private void navAuditorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navAuditorMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_navAuditorMouseClicked

    private void navInfoKlienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navInfoKlienMouseEntered
        // TODO add your handling code here:
        navInfoKlien.setCursor(new Cursor(Cursor.HAND_CURSOR)); 
        navInfoKlien.setBackground(new Color(0, 102, 153));
    }//GEN-LAST:event_navInfoKlienMouseEntered

    private void navInfoKlienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navInfoKlienMouseExited
        // TODO add your handling code here:
        navInfoKlien.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        navInfoKlien.setBackground(new Color(0, 51, 102));
    }//GEN-LAST:event_navInfoKlienMouseExited

    private void navHasilAuditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navHasilAuditMouseClicked
        // TODO add your handling code here:
        LaporanHasilAudit lha = new LaporanHasilAudit();
        close();

        lha.show();

    }//GEN-LAST:event_navHasilAuditMouseClicked

    private void navHasilAuditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navHasilAuditMouseEntered
        // TODO add your handling code here:
        navHasilAudit.setCursor(new Cursor(Cursor.HAND_CURSOR));
        navHasilAudit.setBackground(new Color(0, 102, 153));
    }//GEN-LAST:event_navHasilAuditMouseEntered

    private void navHasilAuditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navHasilAuditMouseExited
        // TODO add your handling code here:
        navHasilAudit.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        navHasilAudit.setBackground(new Color(0, 51, 102));
    }//GEN-LAST:event_navHasilAuditMouseExited

    private void navLaporanKeuanganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navLaporanKeuanganMouseClicked
        // TODO add your handling code here:
        LaporanKeuangan lk = new LaporanKeuangan();
        close();
        
        lk.show();
    }//GEN-LAST:event_navLaporanKeuanganMouseClicked

    private void navLaporanKeuanganMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navLaporanKeuanganMouseEntered
        // TODO add your handling code here:
        navLaporanKeuangan.setCursor(new Cursor(Cursor.HAND_CURSOR));
        navLaporanKeuangan.setBackground(new Color(0, 102, 153));
    }//GEN-LAST:event_navLaporanKeuanganMouseEntered

    private void navLaporanKeuanganMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navLaporanKeuanganMouseExited
        // TODO add your handling code here:
        navLaporanKeuangan.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        navLaporanKeuangan.setBackground(new Color(0, 51, 102));
    }//GEN-LAST:event_navLaporanKeuanganMouseExited

    private void navAfiliatorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navAfiliatorMouseClicked
        // TODO add your handling code here:
        Afiliator af = new Afiliator();
        close();
        
        af.show();
    }//GEN-LAST:event_navAfiliatorMouseClicked

    private void navAfiliatorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navAfiliatorMouseEntered
        // TODO add your handling code here:
        navAfiliator.setCursor(new Cursor(Cursor.HAND_CURSOR));
        navAfiliator.setBackground(new Color(0, 102, 153));
    }//GEN-LAST:event_navAfiliatorMouseEntered

    private void navAfiliatorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navAfiliatorMouseExited
        // TODO add your handling code here:
        navAfiliator.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        navAfiliator.setBackground(new Color(0, 51, 102));
    }//GEN-LAST:event_navAfiliatorMouseExited

    private void navFileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navFileMouseClicked
        // TODO add your handling code here:
        File file = new File();
        close();
        
        file.show();
    }//GEN-LAST:event_navFileMouseClicked

    private void navFileMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navFileMouseEntered
        // TODO add your handling code here:
        navFile.setCursor(new Cursor(Cursor.HAND_CURSOR));
        navFile.setBackground(new Color(0, 102, 153));
    }//GEN-LAST:event_navFileMouseEntered

    private void navFileMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navFileMouseExited
        // TODO add your handling code here:
        navFile.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        navFile.setBackground(new Color(0, 51, 102));
    }//GEN-LAST:event_navFileMouseExited

    private void cetakBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cetakBtnActionPerformed
        // TODO add your handling code here:
        try {
            
            String reportPath = "D:\\KULIAH\\SEMESTER 3\\BASDAT\\PROJECT AKHIR\\projectAkhir\\Jasperreports\\auditor_reports.jrxml";
            JasperReport jr = JasperCompileManager.compileReport(reportPath);
            JasperPrint jp = JasperFillManager.fillReport(jr, null, conn);
            JasperViewer.viewReport(jp);
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_cetakBtnActionPerformed

    private void searchTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchTxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAuditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAuditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAuditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAuditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormAuditor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamatTxt;
    private javax.swing.JTable auditorTbl;
    private javax.swing.JButton cetakBtn;
    private javax.swing.JSpinner gajiSpn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField namaTxt;
    private javax.swing.JPanel navAfiliator;
    private javax.swing.JPanel navAuditor;
    private javax.swing.JPanel navFile;
    private javax.swing.JPanel navHasilAudit;
    private javax.swing.JPanel navInfoKlien;
    private javax.swing.JPanel navLaporanKeuangan;
    private javax.swing.JButton newBtn;
    private javax.swing.JTextField noIDTxt;
    private javax.swing.JButton removeBtn;
    private javax.swing.JButton saveBtn;
    private javax.swing.JTextField searchTxt;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
